### ISSUE TITLE
Need to make a new command for printing blockchain

### ISSUE THREAD

**Issue by phadnisvinay30** [tronprotocol-scala/scala-tron#12]
We also need to mutually decide a command both on the cli and the web api which will print the blockchain (the latest block atleast)

**Comment by Rovak** [comment]
In the PR #10 i've added a web api to show the blocks in the blockchain https://github.com/Rovak/scala-tron/pull/10/files#diff-1d8bb3d0f85fada5715f5a41c257feccR34

I agree that this should also be added in the cli

**Comment by phadnisvinay30** [comment]
okay. I will make a commit which will add the block on the sample output in the readme file which currently has only address and balance
